grails:
    profile: base
    codegen:
        defaultPackage: specification
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
spring:
    jmx:
        unique-names: true
management:
    endpoints:
        enabled-by-default: false
